version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: minidb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: prithvi
    ports:
      - "5432:5432"

  app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    # environment:
    #   DATABASE_URL: "postgresql://postgres:prithvi@db-service:5432/minidb?sslmode=disable"
